### ISSUE TITLE
Market Leader Content in JSON format

### ISSUE THREAD

**Issue by AndrewDiedrich** [makingstax/InfoAndIdeas#1]
@gitmazz can you put all this content for market leaders and what will be on the app in a json file like this? by category then nested providers:
```json
{
  "Endpoint Detection and Response": [
    {
      "name": "Crowdstrike",
      "url": "https://www.crowdstrike.com/products/endpoint-security/"
    },
    {
      "name": "Microsoft Defender for Endpoint",
      "url": "https://www.microsoft.com/en-us/security/business/endpoint-security/microsoft-defender-endpoint"
    }
  ]
}
```
<img width="882" alt="image" src="https://github.com/makingstax/InfoAndIdeas/assets/33077579/6b6e6e23-d9dc-428f-b4c3-127e38b0df50">

**Comment by gitmazz** [comment]
ML.json file added - https://github.com/makingstax/InfoAndIdeas/blob/main/ML.json

Still a work in progress but it's here if you need to reference it
